[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/gosimple/slug"
  version = "=1.1.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "=1.0.3"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/Masterminds/squirrel.v1"
